Map<String, String> arLangMap = {
  "email_user_name": "البريد الإلكتروني / اسم المستخدم",
  "password": "كلمة المرور",
  "forgot_password": "Forgot Password?",
  "click_here": "اضغط هنا",
  "login": "الدخول",
  "dont_have_account": "ليس عضوا",
  "sign_up": "التسجيل",
  "register_now": "سجل الان",
  "welcome": "مرحبا بك في بوك مي",
  "full_name": "الاسم الكامل",
  "user_name": "اسم المستخدم",
  "email": "البريد الالكتروني",
  "phone_number": "رقم الجوال",
  "conform_password": "Conform Password",
  "choose_photo": "اختر صورة",
  "loading": "جاري التحميل...",
  "list_of": "قائمة بـ",
  "locations": "المواقع",
  "home": "الرئيسية",
  "favourites": "المفضلة",
  "reservations": "الحجوزات",
  "profile": "الملف الشخصي",
  "available": "متاح",
  "restaurants": "المطاعم",
  "details": "تفاصيل",
  "reserve": "حجز",
  "directions": "الاتجاهات",
  "call": "اتصال",
  "menu": "قائمة الطعام",
  "rating": "تقييم",
  "description": "الوصف",
  "reserve_table": "قم بحجز طاولة",
  "check_our_delicious": "قم باستكشاف اطعمتنا اللذيذة",
  "guests": "الضيوف",
  "from_date": "التاريخ من",
  "to_date": "التاريخ الى",
  "check_availability": "تحقق من توافر الحجوزات",
  "cancel": "الغاء",
  "confirm_reservation": "تأكيد الحجز ",
  "table": "طاولة",
  "reserved": "محجوزة",
  "table_type": "نوع الطاولة",
  "date_reserved": "تاريخ الحجز",
  "reservation_list": "قائمة الحجوزات",
  "time_reserved": "وقت الحجز",
  "rate_your_experience": "قيم تجربتك",
  "with_our_products": "مع منتجاتنا",
  "would_you_rate": "من 1 الى 5 ماذا كان انطباعك حيال منتجاتنا",
  "any_thing": "مالذي نستطيع تطويرة؟",
  "comments": "التعليقات",
  "submit": "ادخال",
  "logout": "تسجيل خروج",
  "phone_number_required" : "رقم الهاتف مطلوب",
  "full_name_required" : "الإسم الكامل ضروري",
  "user_name_required" : "اسم المستخدم مطلوب",
  "something_went_wrong" : "هناك خطأ ما.",
  "gender" : "جنس تذكير أو تأنيث",
  "male" : "ذكر",
  "female" : "أنثى",
  "other" : "آخر",
  "i_have_read" : "لقد قرأت وأوافق على الشروط والأحكام.",
  "register" : "يسجل",
  "please_read" : "يرجى قراءة الشروط والأحكام أولاً.",
  "personal" : "الشخصية",
  "language" : "لغة",
  "english" : "إنجليزي",
  "arabic" : "عربي",
  "update" : "تحديث",
  "customer" : "عميل",
  "malls" : "مولات",
  "please_select_from_to_date" : "يرجى تحديد من & إلى التاريخ",
  "please_select_from_date" : "يرجى تحديد من التاريخ",
  "please_select_to_date" : "الرجاء التحديد حتى الآن",
  "success" : "النجاح",
  "error" : "خطأ",
  "please_select_table" : "يرجى تحديد الجدول",
  "your_reservation" : "الحجز الخاص بك",
  "you_can_only" : "يمكنك فقط إلغاء الحجز في غضون 12 ساعة من تاريخ الحجز.",
  "no_of_guests" : "لا للضيوف",
  "enter_otp_password" : "أدخل كلمة مرور OTP",
  "proceed" : "تقدم",
  "resend_otp" : "إعادة إرسال OTP",
  "alert" : "انذار",
  "do_you_want_to_add" : "هل تريد ان تضيف",
  "table_no" : "رقم الجدول",
  "in_waiting_list" : "في قائمة الانتظار؟",
  "add" : "يضيف",
};
