Map<String, String> englishLangMap = {
  "email_user_name": "Email / User Name",
  "password": "Password",
  "forgot_password": "Forgot Password?",
  "click_here": "Click Here",
  "login": "Login",
  "dont_have_account": "Not a Member",
  "sign_up": "SignUp",
  "register_now": "Register Now",
  "welcome": "Welcome to Bookme",
  "full_name": "Full Name",
  "user_name": "User Name",
  "email": "Email",
  "phone_number": "Phone Number",
  "conform_password": "Conform Password",
  "choose_photo": "Choose Photo",
  "loading": "Loading...",
  "list_of": "List of",
  "locations": "Locations",
  "home": "Home",
  "favourites": "Favourites",
  "reservations": "Reservations",
  "profile": "Profile",
  "available": "Available",
  "restaurants": "Restaurants",
  "details": "Details",
  "reserve": "Reserve",
  "directions": "Directions",
  "call": "Call",
  "menu": "Menu",
  "rating": "Rating",
  "description": "Description",
  "reserve_table": "Reserve A Table",
  "check_our_delicious": "Check Our Delicious",
  "guests": "Guests",
  "from_date": "From Date",
  "to_date": "To Date",
  "check_availability": "Check Availability",
  "cancel": "Cancel",
  "confirm_reservation": "Confirm Reservation",
  "table": "Table",
  "reserved": "Reserved",
  "table_type": "Table Type",
  "date_reserved": "Date Reserved",
  "reservation_list": "Reservation List",
  "time_reserved": "Time Reserved",
  "rate_your_experience": "Rate Your Experience",
  "with_our_products": "With our products",
  "would_you_rate": "From 1 to 5 how would you rate our product",
  "any_thing": "Anything can be improved?",
  "comments": "Comments",
  "submit": "Submit",
  "logout": "Logout",
  "phone_number_required" : "Phone Number Required",
  "full_name_required" : "Full Name is Required",
  "user_name_required" : "User Name is Required",
  "something_went_wrong" : "Something went wrong.",
  "gender" : "Gender",
  "male" : "Male",
  "female" : "Female",
  "other" : "Other",
  "i_have_read" : "I have read and accept the terms and conditions.",
  "register" : "Register",
  "please_read" : "Please read the terms and conditions first.",
  "personal" : "Personal",
  "language" : "Language",
  "english" : "English",
  "arabic" : "Arabic",
  "update" : "Update",
  "customer" : "Customer",
  "malls" : "Malls",
  "please_select_from_to_date" : "Please Select From & To Date",
  "please_select_from_date" : "Please Select From Date",
  "please_select_to_date" : "Please Select To Date",
  "success" : "Success",
  "error" : "Error",
  "please_select_table" : "Please Select Table",
  "your_reservation" : "Your Reservation",
  "you_can_only" : "You can only cancel the reservation within 12 Hours from the date of reservation.",
  "no_of_guests" : "No of Guests",
  "enter_otp_password" : "Enter OTP Password",
  "proceed" : "Proceed",
  "resend_otp" : "Resend OTP",
  "alert" : "Alert",
  "do_you_want_to_add" : "Do you want to add",
  "table_no" : "Table No",
  "in_waiting_list" : "in waiting list?",
  "add" : "Add",
};
